### ISSUE TITLE
How to use `cardano-node-ogmios` on vasil-dev, preview, or preprod with `v5.5.5`

### ISSUE THREAD

**Issue by rhyslbw** [CardanoSolutions/ogmios#249]
The default configuration used by the `cardano-node-ogmios` Docker images, shipped and pushed to the Docker Hub registry with `v5.5.5`, requires [this commit](https://github.com/input-output-hk/cardano-configurations/commit/303f3a3035c52eb753b533d53ef439c6b4cde9c9) or later to be mounted at runtime or defined as the `CARDANO_CONFIG_REV` build arg, depending on the use-case. See [this commit](https://github.com/input-output-hk/cardano-configurations/commit/319805a02ad4899d1fbdf43cb5db8a494d7e1e50) for details of why this is override is required.

# Docker Hub Registry
First clone the config repo. The current HEAD of _master_ will be compatible: 
```
git clone https://github.com/input-output-hk/cardano-configurations.git
```
## docker
``` console
docker run -v ${PWD}/cardano-configurations/network/preprod:/config ... cardanosolutions/cardano-node-ogmios:v5.5.5_1.35.3-preprod
```
## docker-compose
``` yaml
   cardano-node-ogmios:
      ...
     image: cardanosolutions/cardano-node-ogmios:v5.5.5_1.35.3-preprod
     volumes:
       - ./cardano-configurations/network/preprod:/config
     ...
```

# Building

## docker
``` console
docker build --build-arg CARDANO_CONFIG_REV=303f3a3035c52eb753b533d53ef439c6b4cde9c9 --target cardano-node-ogmios ...
```
## docker-compose
``` yaml
   cardano-node-ogmios:
     build: 
       args:
         - CARDANO_CONFIG_REV=303f3a3035c52eb753b533d53ef439c6b4cde9c9
         - NETWORK=preprod
     ...
```
