### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by ggaabe** [CardanoSolutions/ogmios#279]
#### What Git revision are you using? 
Not sure which revision but it's `5.5.2`
#### What operating system are you using, and which version?

- [X / 20.04.4 LTS] Linux / Ubuntu
- [ ] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 
We experienced a memory leak while ogmios was running in the past couple of days, where it went up to ~40GiB of memory usage and was frequently spiking to 100/130% of CPU usage. Restarting the service seemed to resolve the issue, with memory usage around ~6.832 GiB and CPU usage between 0.82% and 10%
#### What should be the expected behavior?
Memory and CPU usage should probably not rise so high.

**Comment by KtorZ** [comment]
Even ~6.8GB sounds a lot too much for Ogmios. The server doesn't hold anything in memories beyond messages sent by clients.

Questions:

- Are you referring to Ogmios as a standalone process or to the combined cardano-node-ogmios docker image? 

- Are you using the TypeScript client or the server only? If you're the TypeScript client, was it the server or, the client that had a large memory usage? 

- What was your application doing that could've caused the memory leak? More specifically, are you submitting / evaluating many transactions at once? Are you pipelining many 'RequestNext' messages, and if yes, what's the maximum you keep in flight?

- Are you running any expensive queries like getting UTxO by addresses, or querying the list of stake pool rewards info?

**Comment by sk-shishi** [comment]
I'm experiencing the same problem as well on an M1 Pro Macbook.

I run `cardano-node` and `ogmios` separately, via docker-compose
```yaml
version: "3"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.4
    command:
      - run
      - --config
      - /config/cardano-node/config.json
      - --topology
      - /config/cardano-node/topology.json
      - --database-path
      - /db
      - --socket-path
      - /ipc/node.socket
    volumes:
      - ~/blockchain/cardano/db/${CARDANO_NETWORK:?ERROR}:/db
      - ~/blockchain/cardano/config/network/${CARDANO_NETWORK:?ERROR}:/config
      - node-ipc:/ipc
    ports:
      - "3001:13001" # Relay
      - "12788:12788" # EKG
      - "12798:12798" # Prometheus
    user: 0:0
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"

  ogmios:
    image: cardanosolutions/ogmios:latest
    command:
      - --host
      - 0.0.0.0
      - --node-socket
      - /ipc/node.socket
      - --node-config
      - /config/cardano-node/config.json
    volumes:
      - ~/blockchain/cardano/config/network/${CARDANO_NETWORK:?ERROR}:/config
      - node-ipc:/ipc
    ports:
      - "1337:1337" # Both the WebSocket and the HTTP server
    restart: on-failure

volumes:
  node-ipc:
```

The memory usage sometimes spike to around 10-12GB before dropping down and being stable at around 6-7GB. 

`docker stats` output:
```
CONTAINER ID   NAME                       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
65a03b20661a   c-preview-cardano-node-1   209.44%   6.652GiB / 23.45GiB   28.37%    45.4MB / 625kB    47.1MB / 73.7kB   16
1ad10dd20ce9   c-preview-ogmios-1         3.41%     6.667GiB / 23.45GiB   28.43%    4.58kB / 7.24kB   25.3MB / 0B       10
```

`/health` output:
```json
{
  "startTime": "2022-11-25T06:50:50.804648847Z",
  "lastKnownTip": {
    "slot": 720004,
    "hash": "4715768349317f2af6a38eac704ea26e9b09ff3872a83094f760cbe68fbf893f",
    "blockNo": 35447
  },
  "lastTipUpdate": "2022-11-25T06:57:47.096082387Z",
  "networkSynchronization": 0.26632,
  "currentEra": "Babbage",
  "metrics": {
    "activeConnections": 0,
    "runtimeStats": {
      "cpuTime": 19699527965,
      "currentHeapSize": 1254,
      "gcCpuTime": 192865500,
      "maxHeapSize": 316
    },
    "sessionDurations": {
      "max": 0,
      "mean": 0,
      "min": 0
    },
    "totalConnections": 0,
    "totalMessages": 0,
    "totalUnrouted": 0
  },
  "connectionStatus": "connected",
  "currentEpoch": 8,
  "slotInEpoch": 28804
}
```
